Bubble sorting algorithm
El-Potato-Slayer/bubble-sorting pull request #3
Opened 2020-08-18 15:15 UTC by El-Potato-Slayer

The purpose of this project was to create two bubble sorting algorithms; The first bubble sorting algorithm was implement as a normal method, while the second algorithm was meant to work as a block by making use of the "yield" keyword.

2020-08-18 16:34 UTC, bertil291utn commented
**Status:** Invalid 🚫

# Hey guys I hope you're having a great time

I see all your effort work on this project however I have to invalid due to: 

- Please work with Git Flow
Friendly reminder: You should use Github/Git Flow in this project. Please take a step back and watch video here \[LINK to Pathwright lesson\]. Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with correct feature branch . This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

### Summary
- Work with gitflow (master, develop and a feature/branch), create another branch and send a review from there
-  Add more meaningful (*Follow this [guideline](https://cdn.filestackcontent.com/MgHMNfnLRsax5QXjfwHa)*) commits, should be at least 10 commit messages
-Edit your pull request message, Follow this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)
- Please leave just one screenshot in README file

**Note:** to achieve all this check the link that is above this 
<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-18 16:40 UTC, bertil291utn commented
## HEY guys
- Sorry about the above review, was a mistake to mark as invalid, however, while you're in there work on those 2 things and request another review.

I'm sorry for the inconveniences

2020-08-19 16:21 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to follow all the guidelines, you required to do these changes, listed below:

- [ ] Remove all debugging code. Review inline comments below this comment box

### Summary

-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-19 16:21 UTC, bertil291utn commented on bubble_sorting.rb
> +
## Debugging code 
- No debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)
  - [ ] Please remove a debugging code

2020-08-19 16:21 UTC, bertil291utn commented on bubble_sorting.rb
> +end
## Debugging code 
- No debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)
  - [ ] Please remove a debugging code `p`, and return only the arr var

2020-08-20 12:52 UTC, christianotieno approved these changes
# PROJECT APPROVED 🍾 
- All the required changes have been met in this project. I will go ahead and mark this as complete.

Happy Coding Team! 👍

2020-08-20 13:15 UTC, merged